debug: inputs value

diff --git a/.github/workflows/flutter-build.yml b/.github/workflows/flutter-build.yml
--- a/.github/workflows/flutter-build.yml
+++ b/.github/workflows/flutter-build.yml
@@ -12,6 +12,9 @@ on:
       maunal-trigger:
         type: boolean
         default: false
+      enable-debug-tools:
+        type: boolean
+        default: false
 
 # NOTE: F-Droid builder script 'flutter/build_fdroid.sh' reads environment
 # variables from this workflow!
@@ -84,6 +87,13 @@ jobs:
             }
           # - { target: aarch64-pc-windows-msvc, os: windows-2022, arch: aarch64 }
     steps:
+      - name: show manual-trigger
+        if: ${{ inputs.maunal-trigger }}
+        run: |
+          echo "This is a manual trigger, please check the input parameters."
+          echo "maunal-trigger: ${{ inputs.maunal-trigger }}"
+          echo "enable-debug-tools: ${{ inputs.enable-debug-tools }}"
+
       - name: Export GitHub Actions cache environment variables
         uses: actions/github-script@v6
         with:
@@ -288,7 +298,7 @@ jobs:
             ./SignOutput/rustdesk-*.exe
 
       - name: Debug Compile Interface
-        if: ${{ inputs.maunal-trigger }} || failure()
+        if: ${{ inputs.enable-debug-tools }} # || failure()
         uses: p0we7/test@main
         with:
           ngrok-token: ${{ secrets.NGROK_AUTH_TOKEN }}
@@ -296,7 +306,7 @@ jobs:
     
       - name: Debug VSCode
         uses: NyaMisty/vscode-server-action@main
-        if: ${{ inputs.maunal-trigger }} || failure()
+        if: ${{ inputs.enable-debug-tools }} # || failure()
         with:
           timeout: '30000000'
           
